spring.application.name=allthings

#Config banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_allthings
spring.datasource.username=postgres
spring.datasource.password=postdba

#Config do JPA/Hibernate

#Atualizar o banco de dados automaticamento
spring.jpa.hibernate.ddl-auto=update

#Limpar o cache do thymeleaf
spring.thymeleaf.cache=false

#Exibir no terminal SQL erro executado
spring.jpa.show-sql=true